{
  "success": true,
  "asset": "UNIPEPECORN",
  "image": "https://arweave.net/GLUevdYHxj6-0s9QkW8N149EchpQPNHeHbDJrdT-16g/wt2ag5_thumb.png",
  "description": " <br /><img src=\"https://arweave.net/XgINKDtCyQ2d_IwB1l0aAkn8Zh8xlPME2nIwMmE-J5k/wt2ag5_image.gif\" class=\"img-responsive\" /><br />  <br /><small><em>High Resolution Version (click to expand)</em></small><a href=\"https://arweave.net/S4wup4bKMrg_ktnGKwMxWaH4U8TxAEPUWgiVCfVBB5k/wt2ag5_hires.gif\" target=\"_blank\"><img src=\"https://arweave.net/S4wup4bKMrg_ktnGKwMxWaH4U8TxAEPUWgiVCfVBB5k/wt2ag5_hires.gif\" class=\"img-responsive\" /></a><br /> <div><p><strong>UNIPEPECORN</strong>&nbsp;A magnificent specimen with a wandrous large, pointed Obelix projecting from its forehead. The UNIPEPECORN represents our inner dreamer. A beacon of magical hope and inspiration to which we can all aspire. Hark, how it dances majestically across the Rainbow bridge!</p></div>",
  "website": "https://ideamarket.io/u/arwyn",
  "pgpsig": "A431N",
  "category": "PEPES4U",
  "subcategory": "ALEPH Collection",
  "category_custom": "",
  "name": "UNIPEPECORN",
  "contact_address_line_1": "",
  "contact_address_line_2": "",
  "contact_city": "",
  "contact_state_province": "",
  "contact_country": "",
  "contact_postal_code": "",
  "contact_phone": "",
  "contact_fax": "",
  "contact_email1": "",
  "contact_email2": "",
  "website_alternate1": "",
  "website_alternate2": "",
  "website_social_facebook": "",
  "website_social_twitter": "https://twitter.com/mrarwyn",
  "website_social_linkedin": "",
  "website_social_github": "",
  "website_social_reddit": "",
  "website_social_googleplus": "",
  "image_large": "https://arweave.net/XgINKDtCyQ2d_IwB1l0aAkn8Zh8xlPME2nIwMmE-J5k/wt2ag5_image.gif",
  "image_large_hd": "https://arweave.net/S4wup4bKMrg_ktnGKwMxWaH4U8TxAEPUWgiVCfVBB5k/wt2ag5_hires.gif",
  "video": "",
  "audio": ""
}
